### ISSUE TITLE
Release 1.50.1 on pypi

### ISSUE THREAD

**Issue by 4naesthetic** [kcwinner/aws-cdk-appsync-transformer#3]
Hi there! Thanks for your work on this project. Would it be possible to build and publish the latest 1.50.1 version to pypi?

**Comment by kcwinner** [comment]
Thanks for your interest in the project! I'll finish up the Lambda Function piece I'm working on (experimental) and then get this pushed out!

**Comment by kcwinner** [comment]
@seawildau newest version has been published
https://pypi.org/project/aws-cdk-appsync-transformer/

**Comment by 4naesthetic** [comment]
Thanks!
